### PR TITLE
Fix sigma values by correctly converting r_min/2

### PR DESCRIPTION
**Pull request by rmatsum836**
When your ENG 101 professor makes some stump speech about failing NASA launches and unit conversions, turns out he's kind of right.

I would glance over these once more before merging.

### CODE REVIEW

**Comment by rmatsum836** [comment]
Just rechecked the epsilon values and they look okay.  One thing to note is that these parameters are only optimized for TIP3P water.

**Comment by mattwthompson** [comment]
I got the same anecdote as a first-year engineering student.

You got the same sigma values as I did, and the epsilon should be unchanged.

> One thing to note is that these parameters are only optimized for TIP3P water.

I think, until Foyer handles context like this, the best thing to do is just add a comment. I think [this](https://github.com/mattwthompson/aqueous-electrolytes/blob/master/forcefields/dang.xml) syntax works.

**Comment by rmatsum836** [comment]
I added a comment in the xml file specifying these parameters are compatible with TIP3P.  I changed the name of the file from `jc.xml` to `jc_tip3p.xml`.  In a separate PR, I'll add an xml file specifically for SPC/E.

**Comment by mattwthompson** [comment]
Thanks for fixing this.

It's interesting that the parameters are so different for the different water models ...

**Comment by rmatsum836** [comment]
I just noticed that... odd that some of these epsilon values have an order of magnitude difference.

Anyways, I'm good to merge if you are.

**Pull request merged**
